"""Add attachment hash and MIME type

Revision ID: 10a81c6df9fa
Revises: af950c2b3447
Create Date: 2026-08-08 15:57:03.985005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a81c6df9fa'
down_revision = 'af950c2b3447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_sha256', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('attachment_mime_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('attachment_mime_type')
        batch_op.drop_column('attachment_sha256')

    # ### end Alembic commands ###
